before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
before_install: gem install bundler -v 2.0.2
language: ruby
rvm:
- 2.6.3
services:
- postgresql
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  app: upvote-ideas
  on:
    repo: jobannon/upvote_api
  api_key:
    secure: FleddvnHbz0MVK+T6axcsmp5Ns6gfnWo1gUMsWkdHjUdE461xnX4XwMk4XVBnT6dfXgFqjd3OuHPeZ1E9DCKbmuczCvUeY2BxZgx/tAAZ/jwLkuMCXb8aKGBiEMPI90rDj/JuJDdcOfCRev86WsR+fqnT6FQlUU8gxjN8HNacDSxSy6gyEuMH6hoKEQxsto36gOGhaSzFnI7hB8Q/DoOf1wSLk+rsvIKY2tW75jPLAj0QblbwU0fJATyYkEl16U1IIoUp07qION+EUzMNSkY9ofQgMwbUk6DCMhejz8+nHWn6ZoE0U1l+tCwE1S+L/AAjKKJZaOdx2v/iWDxJ2Ri3ZweE5E5m+qWBM0BtkY8z+ZoCoKjKDf/LO9AG8azyR7nd+cf/JEQegkyqbQMGnQxOMsLIQBI+KrekL2NdcW+Emb9PV8RYH49dOx0iYhlJ/DNJsYr5vSAoA4mSkKk6fBIqpiVYVs1XKet4MMRPM83Uh9HmFyXs9JnDqAQzWIuiTvWz9oMrqsWQrADQk4FpZ1p3uetsiXCv1Qpl1lQZnqmmM64SSS7F+/9psy8uifJYGLFRXXkqyJaHPLLtKXbhNl8hvHhZeInX+ONO5IeMYePXQ9dUkjaNTQDzj+6dWiGPR/+wjUycubm/WGEkuv3XJosxRIUAWpmevtAcI+2ZPTkCJI=
